/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JCheckBox;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.Timestamp;
/**
 *
 * @author TOSHIBA
 */
public class MainFrame extends javax.swing.JFrame {
    private String username;
    private String password;
    private String path ="C:\\Users\\TOSHIBA\\Documents\\Tubes5\\";
    
    Socket socket = null;
    PrintWriter out = null;
    BufferedReader in = null;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    public MainFrame(String username, String password, Socket socket, PrintWriter out, BufferedReader in){
        initComponents();

        try {
            this.socket = socket;
            this.out = out;
            this.in = in;

            welcomeLabel.setText("Welcome, "+username);

            String fromserver, fromuser;

            fromuser = "list";
            out.println(fromuser);

            fromserver = in.readLine();
            String[] listtask = fromserver.split("-");

            ArrayList<String> container = new ArrayList<String>();
            for (String s : listtask)
            {
                container.add(s);
            }
            JCheckBox checkbox;

            list.setLayout(new java.awt.GridLayout(container.size(),1));
            for (int i = 0 ; i < container.size(); i++){
                String namestatus = container.get(i);
                String[] attribute = namestatus.split(":");
                checkbox  = new JCheckBox(attribute[0]);
                checkbox.setName(attribute[0]);
                if (attribute[1].equals("COMPLETE")){
                    checkbox.setSelected(true);
                }else{
                    checkbox.setSelected(false);
                }
                checkbox.addActionListener(new Checked());
                list.add(checkbox);
            }
            list.revalidate();
            list.repaint();
        } catch (IOException e) {
            System.err.println("Failed to get list of task");
            System.exit(1);
        }
    }
    
    class Checked implements ActionListener{
        public void actionPerformed(ActionEvent e){
            JCheckBox changed_element = (JCheckBox) e.getSource();
            Timestamp timestamp = new Timestamp(e.getWhen());
            String content = changed_element.getName()+","+timestamp + "," + changed_element.isSelected();
            try {
                File dir = new File(path+"log");
                dir.mkdirs();
                File file = new File(dir, changed_element.getName()+".txt");
                if (!file.exists()){
                    file.createNewFile();
                }else{
                    content = "-"+content;
                }
                    FileWriter fw = new FileWriter(file.getAbsoluteFile(),true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write(content);
                    bw.close();
            }catch (IOException exp){
                exp.printStackTrace();
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        listtask = new javax.swing.JScrollPane();
        list = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        welcomeLabel.setText("Welcome ,");
        welcomeLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        list.setLayout(new java.awt.GridLayout(1, 0));
        listtask.setViewportView(list);

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addComponent(listtask)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listtask, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("frame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        try {
            out.close();
            in.close();
            socket.close();
            Tubes5Client loginform = new Tubes5Client();
            loginform.setVisible(true);
            loginform.setFocusable(true);
            loginform.reset();
            this.setVisible(false);
        } catch (IOException e) {
            System.err.println("Problem with the server");
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel list;
    private javax.swing.JScrollPane listtask;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
